server:
  grpc:
    addr: "0.0.0.0:10200"
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: false
      enable_validate: true
      enable_metadata: true
